export enum EnvVariables {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DATABASE = 'DATABASE_DATABASE',
  ACCESS_SECRET = 'ACCESS_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
  SALT_CRYPT = 'SALT_CRYPT',
}
